export const challengesConfig = [
    { day: 1, tasks: [{ type: 'shadow', count: 2 }, { type: 'math', count: 1 }, { type: 'pattern', count: 1 }], text: "Warm up with Patterns, Shadows and Math!" },
    { day: 2, tasks: [{ type: 'letter', count: 2 }, { type: 'pattern', count: 1 }], text: "Learn your ABCs and Patterns!" },
    { day: 3, tasks: [{ type: 'memory', count: 2 }, { type: 'puzzle', count: 1 }], text: "Brain Training Day!" },
    { day: 4, tasks: [{ type: 'job', count: 2 }, { type: 'number', count: 2 }], text: "Jobs and Numbers!" },
    { day: 5, tasks: [{ type: 'shape', count: 2 }, { type: 'math', count: 2 }, { type: 'pattern', count: 1 }], text: "Shapes, Sums, and Logic!" },
    { day: 6, tasks: [{ type: 'feed', count: 3 }, { type: 'pattern', count: 2 }], text: "Feed the Animals!" },
    { day: 7, tasks: [{ type: 'weather', count: 2 }, { type: 'nature', count: 2 }, { type: 'habitat', count: 1 }], text: "Nature Explorer!" },
    { day: 8, tasks: [{ type: 'puzzle', count: 2 }, { type: 'pattern', count: 2 }], text: "Puzzle and Pattern Master!" },
    { day: 9, tasks: [{ type: 'math', count: 3 }, { type: 'pattern', count: 1 }], text: "Math and Logic Genius!" },
    { day: 10, tasks: [{ type: 'memory', count: 2 }, { type: 'pattern', count: 2 }], text: "Memory and Pattern Champion!" },
    { day: 11, tasks: [{ type: 'shadow', count: 2 }, { type: 'letter', count: 2 }], text: "Visual Fun!" },
    { day: 12, tasks: [{ type: 'job', count: 2 }, { type: 'feed', count: 2 }], text: "Helping Hand!" },
    { day: 13, tasks: [{ type: 'number', count: 3 }, { type: 'pattern', count: 1 }], text: "1-2-3 Count and Predict!" },
    { day: 14, tasks: [{ type: 'shape', count: 2 }, { type: 'habitat', count: 2 }], text: "Homes and Shapes!" },
    { day: 15, tasks: [{ type: 'math', count: 3 }, { type: 'puzzle', count: 2 }], text: "Super Brain!" },
    { day: 16, tasks: [{ type: 'weather', count: 2 }, { type: 'nature', count: 2 }, { type: 'pattern', count: 2 }], text: "Weather Watcher!" },
    { day: 17, tasks: [{ type: 'letter', count: 3 }, { type: 'pattern', count: 1 }], text: "Letter Learner!" },
    { day: 18, tasks: [{ type: 'memory', count: 3 }, { type: 'pattern', count: 2 }], text: "Focus Time!" },
    { day: 19, tasks: [{ type: 'shadow', count: 3 }, { type: 'pattern', count: 1 }], text: "Shadow Ninja!" },
    { day: 20, tasks: [{ type: 'job', count: 3 }, { type: 'habitat', count: 2 }], text: "World Worker!" },
    { day: 21, tasks: [{ type: 'math', count: 4 }, { type: 'pattern', count: 2 }], text: "Math Marathon!" },
    { day: 22, tasks: [{ type: 'puzzle', count: 3 }, { type: 'pattern', count: 2 }], text: "Piece by Piece!" },
    { day: 23, tasks: [{ type: 'feed', count: 2 }, { type: 'nature', count: 2 }, { type: 'pattern', count: 1 }], text: "Nature Lover!" },
    { day: 24, tasks: [{ type: 'number', count: 2 }, { type: 'shape', count: 2 }, { type: 'pattern', count: 2 }], text: "Geometry Fun!" },
    { day: 25, tasks: [{ type: 'letter', count: 3 }, { type: 'math', count: 2 }], text: "School Day!" },
    { day: 26, tasks: [{ type: 'memory', count: 2 }, { type: 'shadow', count: 2 }, { type: 'pattern', count: 2 }], text: "Sharp Eyes!" },
    { day: 27, tasks: [{ type: 'habitat', count: 3 }, { type: 'pattern', count: 2 }], text: "Animal Homes!" },
    { day: 28, tasks: [{ type: 'job', count: 3 }, { type: 'pattern', count: 2 }], text: "Career Day!" },
    { day: 29, tasks: [{ type: 'weather', count: 3 }, { type: 'pattern', count: 2 }], text: "Meteorologist!" },
    { day: 30, tasks: [{ type: 'puzzle', count: 2 }, { type: 'math', count: 2 }, { type: 'memory', count: 2 }, { type: 'letter', count: 2 }, { type: 'pattern', count: 2 }], text: "Grand Finale!" }
];
